### ISSUE TITLE
Question: What is urban-wombat?

### ISSUE THREAD

**Issue by dc0d** [urban-wombat/gotables#7]
What is urban-wombat? Is it a NoSQL database? Can it handle some 2.5 million of records? Does it provide secondary indexes (over that volume of data)?

I ask this because I have been told that `urban-wombat` can replace a CouchDB-Like document/json store even for 1 TB of data.

**Comment by urban-wombat** [comment]
Hi Kaveh

Thanks for taking an interest.

urban-wombat/gotables is an in-memory table format.

It is neither SQL nor a typical no-SQL format.

Because it is in-memory, it probably won't handle millions of records.

It has some binary formats. Probably the most important binary format
is what I am calling FlatTables, which is a tables-only FlatBuffers format.

The FlatTables binary format works and is fast. We will be putting more
work into it to make it even faster.

Regards, Malcolm

An urban wombat is a mythical creature. There is a real wombat that lives
in the Australian bush. But they don't live in the cities.

**Comment by dc0d** [comment]
So if I understand correctly it is meant for config-like data.

**Comment by urban-wombat** [comment]
Config data and messaging. Including large chunks of data.
