### ISSUE TITLE
Networking

### ISSUE THREAD

**Issue by gedw99** [urban-wombat/gotables#8]
Hey.
I have been playing with arrow and qframe. It's pretty slick.

Gotables is looking really useful.
Can you benchmark it against badger and boltdb ?
There are quite a few examples around.
Just a simple one will do.

The proof is in the pudding :)

I am going to try to work on all this for a few days also to see what headway I can make as I have a bit of downtime

**Comment by urban-wombat** [comment]
Hi Ged

Good to hear from you.

I'll have a shot at badger / boltdb / gotables benchmarks.

I did a release of urban-wombat/flattables a month ago, but the response
has been mainly crickets.
https://github.com/urban-wombat/flattables

Doing some benchmarks (if they reflect well on gotables && flattables)
might move things along.
If not, I'll do some tuning.

Cheers, Malcolm

**Comment by urban-wombat** [comment]
All good suggestions.

However, rather than investing effort into benchmarking other libraries, time has
instead been devoted to further tuning of `gotables` and `flattables` (FlatBuffers),
and into providing benchmarks for both:
* `cd gotables; go test -bench=.`
* `cd flattables; go test -bench=.`

Thanks again, Malcolm
